CREATE USER NKP IDENTIFIED BY Nikhitha1Dmdd;
CREATE USER SAHITHI IDENTIFIED BY S1DmddDatabase;
CREATE USER RITHVIK IDENTIFIED BY R1DmddDatabase;
CREATE USER ANOUKSHA IDENTIFIED BY A1DmddDatabase;
GRANT CONNECT,RESOURCE TO NKP;
GRANT CONNECT,RESOURCE TO SAHITHI;
GRANT CONNECT,RESOURCE TO RITHVIK;
GRANT CONNECT,RESOURCE TO ANOUKSHA;
GRANT UNLIMITED TABLESPACE TO SAHITHI;
GRANT UNLIMITED TABLESPACE TO RITHVIK;
GRANT UNLIMITED TABLESPACE TO NKP;
GRANT UNLIMITED TABLESPACE TO ANOUKSHA;
CREATE OR REPLACE TRIGGER Stock_Trigger
 AFTER INSERT OR UPDATE ON NKP.Product_Stock 
 FOR EACH ROW
 BEGIN
 UPDATE NKP.Product SET AVAILABLE_QUANTITY = (AVAILABLE_QUANTITY + :new.Supplied_Quantity) WHERE Product_ID = :new.Product_ID;          
 END;
 /
CREATE OR REPLACE TRIGGER Order_Trigger
 AFTER INSERT OR UPDATE ON NKP.OrderList
 FOR EACH ROW
 BEGIN
 UPDATE NKP.Product SET AVAILABLE_QUANTITY = (AVAILABLE_QUANTITY - :new.quantity) WHERE Product_ID = :new.Product_ID;          
 END;
/
